forum/urls.py
from django.urls import path
from django.conf.urls   import  url
from . import views

app_name='forum'

urlpatterns = [
    #/strona domowa
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(), name='post_detail'),
    #/post/add
    url(r'^post/add/$',views.PostCreate.as_view(),name= 'add_post'),
    #/post/change
    url(r'^post/(?P<pk>[0-9]+)/$',views.PostUpdate, name='update_post'),

    url(r'^post/(?P<pk>[0-9]+)/$',views.DeleteView.as_view(),name='delete'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),

]

piesbook_test/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf .urls.static import static


urlpatterns = [
    path('', include('forum.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.conf import settings
from piesbook_test.settings import MEDIA_URL, MEDIA_ROOT




class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    image = models.FileField()
    created_date = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(
        auto_now_add=True, null=True)

    def get_absolute_url(self):
        return reverse('forum:post_detail',kwargs={'pk':self.pk})



    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

# class Pet(models.Model):
#     Name = models.CharField(max_length=200)
#     Type =

forum/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class UserLog(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username',  'password']

forum/views.py
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login, logout as auth_logout
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.views import generic
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, RedirectView,View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django import forms
from .forms import UserForm,UserLog
from .models import Post
from django.contrib.auth.models import User,AnonymousUser


def logind(self, request):
    if request.user.is_authenticated():
        print("Logged in")
    else:
        print("Not logged in")
    return request.user


class IndexView(generic.ListView):

    template_name = 'forum/posts.html'

    def get_queryset(self):
        return Post.objects.all()

    def log_index(self,request):
        if request.user.is_authenticated():
            print("Logged in")
        else:
            print("Not logged in")
        return request.user


class DetailView(generic.DetailView):
    model = Post

    template_name = 'forum/single_post.html'

class PostCreate(CreateView):
    model = Post
    fields = [  'title', 'image', 'text']

    # template_name = 'forum/post_form.html'
    success_url = reverse_lazy('forum:index')

    def form_valid(self, form):
        us= self.request.user
        
        form.instance.author = us
        return super().form_valid(form)


class PostUpdate(UpdateView):
    model = Post
    fields = ['author','title', 'text']

class PostDelete(DeleteView):
    mode= Post

    url=  reverse_lazy('forum:index')


class UserFormView(View):
    form_class = UserForm
    template_name = 'forum/registration_form.html'


    # wyświetlić prosty formularz
    def get(self,request):
        form = self.form_class(None)
        return render(request,self.template_name,{'form':form})


    #przetwarzanie danych
    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            #normalizacja danych
            username= form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password) # ustawienie hasłą
            user.save()

            user =authenticate(username=username,password=password)

            if user is not None:

                if user.is_active:# sprawdzenie czy nie jest zbanowany
                    login(request,user) #zalogowanie użytkownika
                    return redirect('forum:index')# powrót do strony głónej
        return render(request,self.template_name,{'form':form})


class LoginView(FormView):
    """
    Provides the ability to login as a user with a username and password
    """

    template_name = 'forum/registration_form.html'
    success_url = reverse_lazy('forum:index')
    form_class = AuthenticationForm
    redirect_field_name = REDIRECT_FIELD_NAME

    # wyświetlić prosty formularz
    # def get(self, request):
    #     form = self.form_class(None)
    #     return render(request, self.template_name, {'form': form})
    #
    # def post(self,request):
    #     form = self.form_class(request.POST)
    #
    #     if form.is_valid():
    #         user = form.save(commit=False)
    #         if user is not None:
    #
    #             if user.is_active:# sprawdzenie czy nie jest zbanowany
    #                 login(request,user) #zalogowanie użytkownika
    #                 return redirect('forum:index')# powrót do strony głónej
    #     return render(request,self.template_name,{'form':form})



    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()

        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        auth_login(self.request, form.get_user())

        # If the test cookie worked, go ahead and
        # delete it since its no longer needed
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()

        return super(LoginView, self).form_valid(form)

    # def get_success_url(self):
    #     redirect_to = self.GET.get(self.redirect_field_name)
    #     if not is_safe_url(url=redirect_to, host=self.request.get_host()):
    #         redirect_to = self.success_url
    #     return redirect_to


class LogoutView(RedirectView):
    """
    Provides users the ability to logout
    """
    url = reverse_lazy('forum:index')

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)

    def post(self,request, *args, **kwargs):

        auth_logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)

forum/templates/forum/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>{% block title%} PiesBook{%endblock%}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'forum/style.css' %}"/>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>







</head>
<body>
<! pasek manu>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-hader">
            <!definiowanie przycisków w nagłóku>
            <button type="button" class="navbar-toggle" data-toggle="collaps" data-target="#topNavBar">
                <span class="icon-bar"> </span>
                <span class="icon-bar"> </span>
                <span class="icon-bar"> </span>
                <span class="icon-bar"> </span>
                <span class="icon-bar"> </span>
            </button>
            <!logo po lewej>
            <a class="navbar-brand" href="{% url 'forum:index' %}">Piesbook</a>
        </div>
        <!opis przycisków>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'forum:index'%}">
                        <span class="glyphicons glyphicons-group" aria-hidden="true"></span>&nbsp;
                        Forum
                    </a>
                </li>


            </ul>
            <ul class="nav navbar-nav navbar-right">
                <!przycisk dodaj>

                    <li class="">
                        <a href="#">
                        &nbsp;
                        {{ user.username }}
                        </a>
                    </li>
                    {% if  request.user.is_authenticated %}
                    <li class="">
                        <a href="{% url 'forum:add_post' %}">
                            <span class="glyphicon glyphycon-plus" aria-hidden="true"></span> Dodaj ogłoszenie
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'forum:logout'%}">
                            <span class="glyphicon glyphycon-off" aria-hidden="true"></span> Wyloguj
                        </a>
                    </li>


                    {% else %}
                    <li class="">
                        <a href="{% url 'forum:login'%}">
                            <span class="glyphicon glyphycon-off" aria-hidden="true"></span> Zaloguj
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'forum:register' %}">
                        &nbsp;
                        Rejstracja
                        </a>
                    </li>
                    {%endif%}






            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

forum/templates/forum/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span><! sprawdzenie poprawności tekstu >
        </div>
        <label class="control-label col-sm-2" for="Zgłoszenie:">{{ field.label_tag }}</label>
        <div class="col-sm-100">{{ field }}</div>
    </div>
{% endfor %}

forum/templates/forum/login.html
{% extends 'forum/base.html' %}<! import  bazowego pliku>

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}

<div>
  <td>{{ form.username.label_tag }}</td>
  <td>{{ form.username }}</td>
</div>
<div>
  <td>{{ form.password.label_tag }}</td>
  <td>{{ form.password }}</td>
</div>

<div>
  <input type="submit" value="login" />
  <input type="hidden" name="next" value="{{ next }}" />
</div>
</form>

{# Assumes you setup the password_reset view in your URLconf #}
<p><a href="{% url 'password_reset' %}">Lost password?</a></p>

{% endblock %}

forum/templates/forum/post_form.html
{% extends 'forum/base.html' %}<! import  bazowego pliku>
{% block title %}Nowy Post{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body%}
<div class="containe-fluid">
    <div class="row">
        <div class="col-sm-4 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                         <div class="form-group">
                        {% include 'forum/form_template.html' %}

                            <div class="col-sm-offest-2 col-sm-10">
                                <input type="submit" class="btn btn-success" value="Zatwierdź"></input>
                            </div>

                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}

forum/templates/forum/posts.html
{% extends 'forum/base.html' %}<! import  bazowego pliku>
{% block body%}

<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12">
            <h3>Ogłoszenia</h3>
        </div>

            {% for post in object_list %}
            <div class="col-sm-4 col-lg-3 post">
                <div class="thumvnail">
                    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
                    <link href="https://fonts.googleapis.com/css?family=Questrial" rel="stylesheet">
                    <a href="{%url 'forum:post_detail' post.id%}">
                        <!można tu podlinkować obrazek>

                        <img src= "{{ post.image.url }}" class="img-responsive">
                        <!img src= "{{ post.image }}" class="img-responsive">
                    </a>
                     <div class="caption">
                            <h2>{{ post.title }}</h2>
                            <div class="panel-body"><h4>{{ post.text }}</h4></div>
                     </div>
                        <a href="{% url 'forum:post_detail' post.id %}" class="btn btn-primary btn-sm" role="button">
                            Zobacz więcej</a>
                </div>
            </div>
            {% endfor %}

    </div>

</div>

{% endblock%}

forum/templates/forum/registration_form.html
{% extends 'forum/base.html' %}<! import  bazowego pliku>

{% block title %}Rejstracja{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Konto </h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'forum/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">

                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

forum/templates/forum/single_post.html
{% extends 'forum/base.html' %}<! import  bazowego pliku>
{% block body%}
        <div>
            <h1><a href="{%url 'forum:index' %}"">{{ post.title }}</a></h1>
        </div>

            <div>
                <h3>Autor :  {{ post.author}}</h3>
                <p>opublikowano: {{ post.published_date }}</p>

                <p></p>
            </div>
              <div class="col-sm-4 col-lg-3 post">
                <div class="thumvnail">
                    <a href="{%url 'forum:post_detail' post.id%}">
                        <!można tu podlinkować obrazek>
                        <img src= "{{ post.image.url }}" class="img-responsive">
                        <!img src= "{{ post.image }}" class="img-responsive">
                    </a>
                     <div class="caption">
                            <h2>{{ post.title }}</h2>
                            <p>opublikowano: {{ post.published_date }}</p>

                            <div class="panel-body"><h4>{{ post.text|linebreaksbr }}</h4></div>
                     </div>
                </div>
            </div>
{% endblock%}